version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - local
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - local

  verdaccio:
    image: verdaccio/verdaccio:latest
    environment:
      - VERDACCIO_USERNAME=${VERDACCIO_USERNAME}
      - VERDACCIO_PASSWORD=${VERDACCIO_PASSWORD}
    ports:
      - "4873:4873"
    networks:
      - local

networks:
  local:
    driver: bridge
